<div class="container">
    <p class="text-right h5 mb-4">Bienvenue, Fred Mulet</p>
    <h1>Accueil</h1>

    <div class="row">
        <div class="col-12 col-md-4">
            <div class="card mb-4">
                <div class="card-header bg-dark text-light">
                    Visualisation rapide
                </div>
                <div class="card-body">
                    <p class="card-text">Pour voir tout de suite votre site</p>
                    <a href="#" class="btn btn-primary d-block">Afficher votre site</a>
                </div>
            </div>

            <div class="card">
                <div class="card-header bg-dark text-light">
                    Visualisation rapide
                </div>
                <div class="card-body">
                    <a href="#" class="card-link d-block"><i class="far fa-newspaper"></i> Ajouter un article</a>
                    <a href="#" class="card-link d-block ml-0"><i class="far fa-file"></i> Ajouter une page</a>
                    <a href="#" class="card-link d-block ml-0"><i class="fas fa-user-alt"></i> Ajouter un utilisateur</a>
                </div>
            </div>
        </div>

        <div class="col-12 col-md-8">
            <div class="card">
                <div class="card-header bg-dark text-light">
                    Article rapide
                </div>
                <div class="card-body">
                    <form>
                        <div class="form-group">
                            <label for="titre">Titre de l'article</label>
                            <input type="text" class="form-control" id="titre" aria-describedby="titre" placeholder="Titre">
                        </div>
                        <div class="form-group">
                            <label for="texte">Texte de l'article</label>
                            <textarea class="form-control" id="texte"></textarea>
                        </div>
                        <div class="form-check">
                            <div class="form-check-inline">
                                <input class="form-check-input" type="radio" name="inlineRadioOptions" id="publier" value="publier" checked>
                                <label class="form-check-label" for="publier">
                                    Publier
                                </label>
                            </div>
                            <div class="form-check-inline">
                                <input class="form-check-input" type="radio" name="inlineRadioOptions" id="brouillon" value="brouillon">
                                <label class="form-check-label" for="brouillon">
                                    Brouillon
                                </label>
                            </div>
                        </div>
                        <button type="submit" class="btn btn-primary">Enregistrer</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <div class="row mt-5">
        <div class="col-12 col-md-8">
            <div class="card">
                    <div class="card-header bg-dark text-light h5">
                    Liste des derniers articles
                </div>
                <div class="list-group list-group-flush">
                    <div class="list-group-item">
                        <h6>Article1</h6>
                        <p>début du texte de l'article (...)</p>
                        <blockquote class="blockquote-footer">Auteur : <em>Fred</em></blockquote>
                    </div>
                    <div class="list-group-item">
                        <h6>Article2</h6>
                        <p>début du texte de l'article (...)</p>
                        <blockquote class="blockquote-footer">Auteur : <em>Fred</em></blockquote>
                    </div>
                    <div class="list-group-item">
                        <h6>Article3</h6>
                        <p>début du texte de l'article (...)</p>
                        <blockquote class="blockquote-footer">Auteur : <em>Fred</em></blockquote>
                    </div>
                    <div class="list-group-item">
                        <h6>Article4</h6>
                        <p>début du texte de l'article (...)</p>
                        <blockquote class="blockquote-footer">Auteur : <em>Fred</em></blockquote>
                    </div>
                </div>
            </div>
            <a href="#">Voir tous les articles</a>
        </div>

        <div class="col-12 col-md-4">
            <div class="card">
                <div class="card-header bg-dark text-light h5">
                    Liste des derniers commentaires
                </div>
                <div class="list-group list-group-flush">
                    <div class="list-group-item">
                        <p class="h6">Lorem ipsum dolor sit amet, consectetur (...)</p>
                        <blockquote class="blockquote-footer text-right">De <em>Jean Bob</em></blockquote>
                    </div>
                    <div class="list-group-item">
                        <p>Lorem ipsum dolor sit amet, consectetur (...)</p>
                        <blockquote class="blockquote-footer text-right">De <em>Jean Karine</em></blockquote>
                    </div>
                    <div class="list-group-item">
                        <p>Lorem ipsum dolor sit amet, consectetur (...)</p>
                        <blockquote class="blockquote-footer text-right">De <em>Jean Fred</em></blockquote>
                    </div>
                    <div class="list-group-item">
                        <p>Lorem ipsum dolor sit amet, consectetur (...)</p>
                        <blockquote class="blockquote-footer text-right">De <em>Jeanne Sabine</em></blockquote>
                    </div>
                </div>
            </div>
            <a href="#">Voir tous les commentaires</a>
        </div>
    </div>
</div>   
