<div class="container mt-5">
    <div class="col-12 col-md-12">
        <div class="card">
            <div class="card-header bg-dark text-light">
                Saisie d'un utilisateur
            </div>
            <div class="card-body">

                <?php if (count($error) != 0 ): ?>
                    <div class="alert alert-danger" role="alert">
                        <?php foreach ($error as $value) : ?>
                            <p><?= $value ?></p>
                        <?php endforeach ?>
                    </div>
                <?php endif ?>

                <form method="post" action="login.php">
                    <div class="form-group">
                        <label for="email">Votre email</label>
                        <input type="email" class="form-control" id="email" name="email" aria-describedby="email" required value="<?= $email; ?>">
                    </div>
                    <div class="form-group">
                        <label for="password">Votre mot de passe</label>
                        <input type="password" class="form-control" id="password" name="password" required value="<?= $password; ?>">
                    </div>
                    <input type="submit" class="btn btn-primary">
                </form>
                
            </div>
        </div>
    </div>
</div>
